version: '3.7'

services:
  builder:
    image: node:12
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    working_dir: /app
    command: bash -c "yarn && yarn build"

volumes:
  node_modules:
