version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./_db_init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=movies_db
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - "postgres"

volumes:
  db_data:
